### ISSUE TITLE
Having trouble getting started on Alfresco Community 5.0a

### ISSUE THREAD

**Issue by GoogleCodeExporter** [douglascrp/alfresco-cloud-store#4]
```
What steps will reproduce the problem?
1. service alfresco stop
2. java -jar alfresco-mmt.jar install 
/opt/alfresco/amps/alfresco-cloud-store.amp 
/opt/alfresco/tomcat/webapps/alfresco.war -force (also tried manually unpacking 
AMP..)
3. directly modify XML for Authentication with S3 (access key, secret key, 
bucket name etc)
4. rename caching-content-store-context.xml.sample 
caching-content-store-context.xml
5. Rename replicating-content-services-context.xml.sample 
replicating-content-services-context.xml
6. service alfresco restart && tail -f -n 100 
/opt/alfresco/tomcat/logs/catalina.out

What is the expected output? What do you see instead?
Expected - Content store begins replicating from local to s3


What version of the product are you using? On what operating system?
using the latest version available on alfresco community 5.0a
running on amazon linux ami (enterprise linux)
Amazon ec2 server
MySQL Database

Please provide any additional information below.

I'm sorry, I'm very new to alfresco and not a developer... not sure how to 
proceed past this error. Thanks


2015-02-19 18:33:15,262  ERROR [web.context.ContextLoader] 
[localhost-startStop-1] Context initialization failed
 org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'authorityBridgeTableCache' defined in class path resource [alfresco/cache-context.xml]: Cannot resolve reference to bean 'authorityBridgeDAO' while setting bean property 'authorityBridgeDAO'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'authorityBridgeDAO' defined in class path resource [alfresco/authority-services-context.xml]: Cannot resolve reference to bean 'nodeDAO' while setting bean property 'nodeDAO'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'nodeDAO': FactoryBean threw exception on object creation; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'nodeDAO.org.hibernate.dialect.MySQLInnoDBDialect' defined in class path resource [alfresco/dao/dao-context.xml]: Cannot resolve reference to bean 'contentDataDAO' while setting bean property 'contentDataDAO'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'contentDataDAO' defined in class path resource [alfresco/dao/dao-context.xml]: Cannot resolve reference to bean 'eagerContentStoreCleaner' while setting bean property 'contentStoreCleaner'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'eagerContentStoreCleaner' defined in class path resource [alfresco/content-services-context.xml]: Cannot resolve reference to bean 'contentStoresToClean' while setting bean property 'stores'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'contentStoresToClean' defined in class path resource [alfresco/content-services-context.xml]: Cannot resolve reference to bean 'fileContentStore' while setting constructor argument with key [0]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'fileContentStore' defined in file [/opt/alfresco/tomcat/webapps/alfresco/WEB-INF/classes/alfresco/module/cloudstore/module-context.xml]: Cannot resolve reference to bean 'contentCache' while setting bean property 'cache'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'contentCache' defined in file [/opt/alfresco/tomcat/webapps/alfresco/WEB-INF/classes/alfresco/module/cloudstore/module-context.xml]: Cannot resolve reference to bean 'cachingContentStoreCache' while setting bean property 'memoryStore'; nested exception is org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [org.alfresco.repo.cache.EhCacheAdapter] for bean with name 'cachingContentStoreCache' defined in file [/opt/alfresco/tomcat/webapps/alfresco/WEB-INF/classes/alfresco/module/cloudstore/module-context.xml]; nested exception is java.lang.ClassNotFoundException: org.alfresco.repo.cache.EhCacheAdapter
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:328)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:106)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1325)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1086)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:291)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:288)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:190)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:580)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:895)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:425)
	at org.springframework.web.context.ContextLoader.createWebApplicationContext(ContextLoader.java:276)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:197)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:47)
	at org.alfresco.web.app.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:63)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4973)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5467)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:632)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1073)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1857)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

(The comment was too long so I attached a file with the entire error..) 

```

Original issue reported on code.google.com by `ji...@creativestudios.com.au` on 19 Feb 2015 at 8:13

Attachments:
* [alfresco-module-error](https://storage.googleapis.com/google-code-attachments/alfresco-cloud-store/issue-4/comment-0/alfresco-module-error)

**Comment by douglascrp** [comment]
Closing
